export const bgMap = {
  '01d': 'clear',
  '01n': 'clear-night',
  '02d': 'cloudy',
  '02n': 'cloudy-night',
  '03d': 'cloudy',
  '03n': 'cloudy-night',
  '04d': 'cloudy',
  '04n': 'cloudy-night',
  '09d': 'rain',
  '09n': 'rain',
  '10d': 'rain',
  '10n': 'rain',
  '11d': 'thunderstorm',
  '11n': 'thunderstorm',
  '13d': 'snow',
  '13n': 'snow-night',
  '50d': 'mist',
  '50n': 'mist-night',
};

export const directions = [
  'N',
  'N-NE',
  'NE',
  'E-NE',
  'E',
  'E-SE',
  'SE',
  'S-SE',
  'S',
  'S-SW',
  'SW',
  'W-SW',
  'W',
  'W-NW',
  'NW',
  'N-NW',
];
